// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// neighbors
List neighbors(NumericMatrix posAndBetas);
RcppExport SEXP _boostme_neighbors(SEXP posAndBetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type posAndBetas(posAndBetasSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbors(posAndBetas));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boostme_neighbors", (DL_FUNC) &_boostme_neighbors, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_boostme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
