# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the nearest non-missing neighbor betas and distances
#'
#' This function finds the nearest non-missing neighboring CpG methylation
#' values upstream and downstream for each CpG.
#'
#' @param posAndBetas A numeric matrix that looks like:
#' chr  pos  beta
#' 1    5000 0.1
#' 1    5012 0.9
#' ...
#' 3    10020 0.01
#' 3    10112 0.09
#' (with some NAs in there)
#' @export
NULL

neighbors <- function(posAndBetas) {
    .Call('_boostme_neighbors', PACKAGE = 'boostme', posAndBetas)
}

